import Head from 'next/head'
import React from 'react'
import NavBar from '../compontents/NavBar'
import Footer from '../compontents/Footer'
const Layout = ({ children }) => {
    return (
        <>
            <Head><title>header</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link> */}
            </Head>
            <NavBar />
            <main>{children}</main>
            <Footer />
        </>
    )
}

export default Layout;  // Default export
